title: Secure Lightweight Kubernetes Package Manager
baseurl: https://kubepack.com
languageCode: en-us
pluralizeListTitles: false
pygmentsStyle: "monokai"
pygmentsUseClasses: false
disqusShortname: appscode
staticdir: "build"
taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
params:
  author: Kubepack Authors
  date_format: Mon, Jan 2, 2006
  description: Secure Lightweight Kubernetes Package Manager
  email: kubepack@appscode.com
  logo: /images/logo.svg
  twitter_url: https://twitter.com/Kubepack
  slack_url: http://slack.kubernetes.io/
  issues_url: https://github.com/kubepack/pack/issues/new
  youtube_url: https://www.youtube.com/c/appscode
  docker_url: https://hub.docker.com/u/kubepack
  contact_email: kubepack@appscode.com
  sales_email: sales@appscode.com
  contact_phone: +1 (650) 241-8486
menu:
  main:
    - Name: "Documentation"
      Weight: 1
    - Name:
      Pre: "<i class='fa fa-github'></i>"
      Weight: 2
      Identifier: "GitHub"
      URL: "https://github.com/kubepack"
    - Name:
      Pre: "<i class='fa fa-twitter'></i>"
      Weight: 3
      Identifier: "twitter"
      URL: "https://twitter.com/Kubepack"
    - Name:
      Pre: "<i class='fa fa-users'></i>"
      Weight: 4
      Identifier: "groups"
      URL: "https://groups.google.com/forum/#!forum/kubepack"
    - Name:
      Pre: "<i class='fa fa-slack'></i>"
      Weight: 5
      Identifier: "slack"
      URL: "http://slack.kubernetes.io/"

