apiVersion: v1
kind: Service
metadata:
  annotations:
    git-commit-hash: b1216d2df51f7f5cd87a2df4b2896cdb50646d98
  labels:
    app: nginx
  name: nginx
spec:
  clusterIP: None
  ports:
  - name: web
    port: 80
  selector:
    app: nginx
