apiVersion: v1
kind: Pod
metadata:
  annotations:
    git-commit-hash: b1216d2df51f7f5cd87a2df4b2896cdb50646d98
  name: test-pd
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - hostPath:
      path: /tmp
    name: test-volume
