apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    git-commit-hash: e69be3069044bf99611ca7fe07d26515b3a1ead1
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        app: nginx
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
