apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    git-commit-hash: 14f51ecf7e626588776358eb4bc5add7926642eb
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        app: nginx
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
