apiVersion: v1
kind: Pod
metadata:
  annotations:
    git-commit-hash: b1216d2df51f7f5cd87a2df4b2896cdb50646d98
  name: test-ebs
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: test-volume
  volumes:
  - awsElasticBlockStore:
      fsType: ext4
      volumeID: vol-02dcd863d6b09b41c
    name: test-volume
